[package]
name = "attractor-rs"
version = "0.1.0"
edition = "2024"
authors = ["Jason Sochin <jsochin8@gmail.com>"]
description = "A cyclically symmetric chaos visualizer, written in Rust"
license = "MIT"

[dependencies]
eframe = "0.28"
egui = "0.28"